<?php

/**
 * Extension Name: Caching Output
 * Extension URI:
 * Description: Uses Cache_Lite to compress and cache output.
 * Version: 0.1
 * Copyright: Nexista
 * Author: Albert Lash
 * License: LGPL
 * Status: beta
 *
 * PHP version 5
 *
 * @category Nexista_Extensions
 * @package  Nexista_Cache
 * @author   Albert Lash <albert.lash@gmail.com>
 * @license  http://www.gnu.org LGPL
 * @version  SVN: 123
 * @link     http://www.nexista.org/
 *
 */

/*
Configuration:

<nexista_cache>
    <placement>prepend</placement>
    <source>&includepath;extensions/nexista_cache.php</source>
    <active>1</active>
    <timers>1</timers>
    <excludes></excludes>
    <purge_gates>list-of-gates,logout</purge_gates>
    <purge_gets>from_date</purge_gets>
</nexista_cache>
*/

/* PURGE CACHE */
if ( // POST will always purge the cache
    count($_POST) > 0 ||
    // need a foreach loop here
    $_GET['from_date'] ||
    // and here
    $_GET['nid']=="logout" ) {
    $gate_cache_file = NX_PATH_CACHE.'cache_*';

    foreach (glob("$gate_cache_file") as $filename) {
        unlink($filename);
    }
}


/* Handle Exclusions */




Nexista_Init::registerOutputHandler('Nexista_cache');

/**
 * nexista_cache
 *
 * Output buffer utilizing PEAR_Cache
 *
 * @param object $init includes stuff
 *
 * @return boolean
 */
function Nexista_cache($init)
{

    //configuration - move to xml
    $timers = false;
    $active = true;

    //necessary stuff no matter what
    $uid = Nexista_Flow::get('//runtime/user_id');
    $uri = $_SERVER['REQUEST_URI'];
    $cac = NX_PATH_CACHE . 'cache_' . md5($uid) . '_' . md5($uri);

    //first things first - check for if-modified-since
    if ($ims = $_SERVER['HTTP_IF_MODIFIED_SINCE']) {
        if (is_file($cac)) {
            $ims = strtotime($ims);
            $lm  = filemtime($cac);
            if ($lm == $ims) {
                header("HTTP/1.1 304 Not Modified");
                exit;
            }
        }
    }


    $init->process();
    $content_type = $init->getInfo('content_type');
    $cache_control = $init->getInfo('cache_control');

    if (!is_dir(NX_PATH_CACHE))
        @mkdir(NX_PATH_CACHE, 0777, true);

    include_once 'Cache/Lite.php';

    ob_start();
    ob_start();


    // Server cache
    $expiryTime = $init->getInfo('cacheExpiryTime');

    $active = Nexista_Config::get("./extensions/nexista_cache/active");

    $options = array(
            'cacheDir' => NX_PATH_CACHE,
            'caching'  => $active,
            'lifeTime' => $expiryTime
            );

    $cache = new Cache_Lite($options);

    if ($output = $cache->get($uri, $uid, true)) {
        $cache_type = "file cache";
        $lm = filemtime($cac);
        header("Last-Modified: " . gmdate('D, d M Y H:i:s', $lm) . " GMT");

    } else {

        header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
        $cache_type = "no cache";

        $output = $init->run();

        if ($timers) {
            $server_time = Nexista_Debug::profile();

            if ( $content_type == "text/html" ) {
                $output = str_replace("</body>", "", $output);
                $output = str_replace("</html>", "", $output);

                $output .= "\n\n<!--\nOriginal request required: $server_time!\n-->\n\n";
                $output .= "</body></html>";
            } elseif ( $content_type == "text/css" ) {
                $output .=  "\n/* Original request required: $server_time! */";
            }
        }
        $cache->save($output, $uri, $uid);
    }

    if ( $content_type == "text/html" ) {
        $output = str_replace("</body>", "", $output);
        $output = str_replace("</html>", "", $output);
    }

    echo $output;
    if ($timers) {
        $server_time = Nexista_Debug::profile();

        if ( $content_type == "text/html" ) {
            echo "<!--\n";
            echo "Nexista Cache Information:\n";
            echo "Output generated by $cache_type in $server_time.\n";
            echo "Output sent with Cache-Control: $cache_control headers, which will affect future requests.\n";
            if ($lm > 0) {
                echo "Cache created: ". gmdate('D, d M Y H:i:s', $lm) . " GMT\n";
            }
            echo "Current time: " . gmdate('D, d M Y H:i:s') . " GMT\n-->\n";
            echo "</body></html>";
        } elseif ( $content_type == "text/css" ) {
            echo "\n/* Output generated by $cache_type in $server_time. */";
        } elseif ( $content_type == "text/x-javascript" ) {
            echo "\n// Output generated by $cache_type in $server_time.";
        }
    }
    ob_end_flush();
    header("Content-Length: ".ob_get_length());
    ob_end_flush();

}
